LWC_WorkReport/force-app/main/default/objects/i3s_Log__e/i3s_Log__e.object-meta.xml
<CustomObject>
    <label>ログ情報</label>
</CustomObject>

LWC_WorkReport/force-app/main/default/objects/i3s_Log__e/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>アクション名（主に画面側で設定する）</description>
    <label>アクション</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LWC_WorkReport/force-app/main/default/objects/i3s_Log__e/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>ログ詳細（エラー等）を設定する。</description>
    <label>詳細</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

LWC_WorkReport/force-app/main/default/objects/i3s_Log__e/fields/OperationDatetime__c.field-meta.xml
<CustomField>
    <fullName>OperationDatetime__c</fullName>
    <label>操作時間</label>
    <type>DateTime</type>
</CustomField>

LWC_WorkReport/force-app/main/default/objects/i3s_Log__e/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>該当の操作/処理を行ったユーザ名</description>
    <label>ユーザ名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LWC_WorkReport/force-app/main/default/classes/i3s_LoggerCtrl.cls
public with sharing class i3s_LoggerCtrl {
    @AuraEnabled
    public static void createLog(String action, String detail) {
        i3s_Log__e newsEvent = new i3s_Log__e (
            Action__c = action,
            UserName__c = UserInfo.getName(),
            OperationDatetime__c = System.Now(),
            Detail__c = detail
        );
        // イベントを公開する
        Database.SaveResult sr = EventBus.publish(newsEvent);
        if (!sr.isSuccess()) {
            String message = '';
            for (Database.Error err : sr.getErrors()) {
                message += (message == '' ? '' : '\n') + err.getMessage();
            }
            throw new AuraHandledException(message);
        }
    }

}